### ISSUE TITLE
[question] CMS 2021? Dual game option?

### ISSUE THREAD

**Issue by elektronemulo** [Curs0r/apu#3]
Would it be possible for you to update this for CMS 2021?

Would it be possible for you to select CMS 2018 or CMS 2021 on startup?

**Comment by Curs0r** [comment]
I am not planning to do any more to it myself. I was approached by someone yesterday about a fork. I think it's probably being worked on. I don't have the new CMS and am not planning to purchase it. Thanks for using the utility though. Weird how much software I've written that nobody cared about, but this keeps going :)
