### ISSUE TITLE
I broke the path (on purpose) - Now I can't find a way to reset it

### ISSUE THREAD

**Issue by elektronemulo** [Curs0r/apu#4]
Hello there, you wonderful savior of bored junkyard mechanics!

I tried manually pointing the app at my CMS 2021 folder (which obviously didn't work). (Then I opened the code and found that the cms2018_Data level of the directory path is hard-coded,)

My issue is that the app has saved the BAD path and I see no obvious way to reset the APU saved path configuration. If I could do this, I could force the path detection routine to run again so I can use it on my CMS 2018 files. Thanks for a fantastic little app.

**Comment by Curs0r** [comment]
It should be in your AppData folder. C:\Users\YourName\AppData etc.
